// Mock data for development when WooCommerce API is not available
import type { Product, Category, Money } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Curso Básico de Skateboarding',
    slug: 'curso-basico-skateboarding',
    handle: 'curso-basico-skateboarding',
    title: 'Curso Básico de Skateboarding',
    description: 'Aprende los fundamentos del skateboarding desde cero con nuestros expertos.',
    descriptionHtml: '<p>Aprende los fundamentos del skateboarding desde cero con nuestros expertos.</p>',
    short_description: 'Curso completo para principiantes',
    price: '49.99',
    regular_price: '49.99',
    sale_price: '',
    priceRange: {
      minVariantPrice: { amount: '49.99', currencyCode: 'EUR' },
      maxVariantPrice: { amount: '49.99', currencyCode: 'EUR' },
    },
    compareAtPriceRange: {
      maxVariantPrice: { amount: '49.99', currencyCode: 'EUR' },
    },
    on_sale: false,
    stock_status: 'instock',
    availableForSale: true,
    categories: [{ id: 1, name: 'Cursos', slug: 'cursos', description: '', count: 3 }],
    collections: [{ id: 1, name: 'Cursos', slug: 'cursos', description: '', count: 3 }],
    tags: [{ id: 1, name: 'principiante', slug: 'principiante' }],
    images: [
      {
        id: 1,
        src: '/images/skate-bundle01.png',
        url: '/images/skate-bundle01.png',
        alt: 'Curso Básico',
        altText: 'Curso Básico',
        width: 800,
        height: 600,
      },
    ],
    featuredImage: {
      id: 1,
      src: '/images/skate-bundle01.png',
      url: '/images/skate-bundle01.png',
      alt: 'Curso Básico',
      altText: 'Curso Básico',
      width: 800,
      height: 600,
    },
    attributes: [],
    options: [],
    variations: [],
    variants: [
      {
        id: 1,
        title: 'Default',
        price: '49.99',
        regular_price: '49.99',
        sale_price: '',
        stock_status: 'instock',
        availableForSale: true,
        attributes: [],
        selectedOptions: [],
      },
    ],
    vendor: 'AuroraSkate',
    seo: {
      title: 'Curso Básico de Skateboarding',
      description: 'Aprende los fundamentos del skateboarding desde cero',
    },
    updatedAt: new Date().toISOString(),
    date_modified: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Curso Avanzado de Tricks',
    slug: 'curso-avanzado-tricks',
    handle: 'curso-avanzado-tricks',
    title: 'Curso Avanzado de Tricks',
    description: 'Domina los trucos más avanzados con técnicas profesionales.',
    descriptionHtml: '<p>Domina los trucos más avanzados con técnicas profesionales.</p>',
    short_description: 'Para skaters experimentados',
    price: '79.99',
    regular_price: '99.99',
    sale_price: '79.99',
    priceRange: {
      minVariantPrice: { amount: '79.99', currencyCode: 'EUR' },
      maxVariantPrice: { amount: '99.99', currencyCode: 'EUR' },
    },
    compareAtPriceRange: {
      maxVariantPrice: { amount: '99.99', currencyCode: 'EUR' },
    },
    on_sale: true,
    stock_status: 'instock',
    availableForSale: true,
    categories: [{ id: 1, name: 'Cursos', slug: 'cursos', description: '', count: 3 }],
    collections: [{ id: 1, name: 'Cursos', slug: 'cursos', description: '', count: 3 }],
    tags: [{ id: 2, name: 'avanzado', slug: 'avanzado' }],
    images: [
      {
        id: 2,
        src: '/images/skate-bundle02.png',
        url: '/images/skate-bundle02.png',
        alt: 'Curso Avanzado',
        altText: 'Curso Avanzado',
        width: 800,
        height: 600,
      },
    ],
    featuredImage: {
      id: 2,
      src: '/images/skate-bundle02.png',
      url: '/images/skate-bundle02.png',
      alt: 'Curso Avanzado',
      altText: 'Curso Avanzado',
      width: 800,
      height: 600,
    },
    attributes: [],
    options: [],
    variations: [],
    variants: [
      {
        id: 2,
        title: 'Default',
        price: '79.99',
        regular_price: '99.99',
        sale_price: '79.99',
        stock_status: 'instock',
        availableForSale: true,
        attributes: [],
        selectedOptions: [],
      },
    ],
    vendor: 'AuroraSkate',
    seo: {
      title: 'Curso Avanzado de Tricks',
      description: 'Domina los trucos más avanzados',
    },
    updatedAt: new Date().toISOString(),
    date_modified: new Date().toISOString(),
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 1,
    name: 'Cursos',
    slug: 'cursos',
    description: 'Todos nuestros cursos de skateboarding',
    count: 2,
  },
];

export const USE_MOCK_DATA = import.meta.env.PUBLIC_USE_MOCK_DATA === 'true';
